Adding avg percent extension post processor
idaholab/blackbear pull request #252
Opened 2021-09-03 12:43 UTC by jain651

# Reason

Extension between two points in a numerical domain is required to compare modeling result to the experimentally observed results. Currently to calculate extension between two points in a domain, we need to obtain displacement in each direction (using PointValue postprocessor) for individual points and then manually obtain the deformation.

# Design

A new postprocessor is required that automatically gather the extension in each pair of points and average them to provide average extension between a pair to points.

# Impact

Reduces the length and better handling of input file and possible error in the manual calculations.

#251

2021-09-03 12:44 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/812979/) on 6ce760c wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/blackbear/docs/PRs/252/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/blackbear/docs/PRs/252/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c77040ff2b61f88092b606e7f964923f7a20d0ba`

2021-09-03 13:16 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/812983/) on fdba4cf wanted to post the following:

View the site [here](https://mooseframework.inl.gov/blackbear/docs/PRs/252/site)

This comment will be updated on new commits.

2021-09-03 14:07 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/812986/) on f1c9efe wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/blackbear/docs/PRs/252/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/blackbear/docs/PRs/252/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format c77040ff2b61f88092b606e7f964923f7a20d0ba`

2021-09-03 16:18 UTC, jain651 commented
@bwspenc this PR is ready for review

2021-09-03 20:59 UTC, bwspenc requested changes
Looks good -- just a minor change requested.

My only remaining concern on this is that I'm not sure whether this should compute the percentage. It seems more natural to me to just report delta L / L. Is that called "extension" or "extension ratio"? I'm not quite sure.  I always call it "delta L over L"! https://en.wikipedia.org/wiki/Deformation_(physics)

2021-09-03 20:59 UTC, bwspenc commented on doc/content/source/postprocessor/AveragePercentExtension.md
> +This `PostProcessor` computes average percentage extension between a set of points specified in two array `first_point` and `last_point`.
between two sets of points specified in two arrays:

Also, it's probably also worth stating that: The extensions between the points with matching positions in these arrays are computed, and then their average is computed. The lengths of these sets of points must be the same.

2021-09-04 19:09 UTC, bwspenc commented
You were going to change the name to AverageExtensionRatio, right?

2021-09-04 19:47 UTC, bwspenc commented on test/tests/AverageExtensionRatio/tests
> +    requirement = "AverageExtensionRatio computes the average extension ratio between two sets of points specified in two arrays: `first_point` and `last_point`. It should result in error when sizes
A few minor issues here:
1) There doesn't appear to be a test of the postprocessor under standard conditions.
2) If you're going to re-use the same -i file like you're doing for the error tests (which is a good idea), you should add `prereq` so they don't all run at the same time.
3) The way you have the requirements specified isn't really the best.  I think I wouldn't use `detail` in this case. I'd just have three tests with three requirements:
- The system shall provide a postprocessor that computes the average extension ratio between two sets of points.
- AverageExtensionRatio shall generate an error if the sizes of the specified sets of points do not match.
- AverageExtensionRatio shall generate an error if the size of either of the sets of points is zero.

2021-09-04 19:48 UTC, bwspenc requested changes
This looks good, just needs some minor work on the tests as noted.

2021-09-04 23:38 UTC, bwspenc approved these changes

2021-09-05 05:34 UTC, merged

2021-09-05 05:36 UTC, bwspenc commented
By the way, you don't need to repeat the stuff in the issue in the pull request. Just say 'closes #251'.