Fix #303 eliminate _use_old_damage for threshold
idaholab/blackbear pull request #304
Opened 2022-06-21 18:53 UTC by maxnezdyur

Only use _omega for the threshold.
Convergence seems to be just as quick when using _use_old_damage
Had to update the tests because damage index changed to 0.999 one time step faster.
Changed "heavy" tests also

2022-06-21 18:53 UTC, maxnezdyur commented
@bwspenc What we talked about earlier.

2022-06-21 19:55 UTC, bwspenc requested changes
I discussed this with @recuero and we agree that we should go ahead and make this change. Just one thing here -- it looks like you're adding a csv file that wasn't there before. Without having looked at the 'tests' file, my guess is that it isn't needed because it wasn't there before. It's probably an 'exodiff' rather than a 'csvdiff' test. Just delete the csv file in the gold directory and this should be good to go.

2022-06-21 19:58 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/1084602/) on e04f8c7 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/blackbear/docs/PRs/304/site)

This comment will be updated on new commits.

2022-06-21 20:01 UTC, bwspenc approved these changes

2022-06-23 00:43 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1084814/) on 70759f5 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>031055</th>
      <th colspan=4>#304 70759f</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>95.69%</td>
      <td>95.76%</td>
      <td>+0.07%</td>
      <td>100.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>1289</td>
      <td>1288</td>
      <td>-1</td>
      <td>1</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>58</td>
      <td>57</td>
      <td>-1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/blackbear/docs/PRs/304/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/blackbear/docs/PRs/304/coverage)



This comment will be updated on new commits.

2022-06-23 14:32 UTC, recuero approved these changes

2022-06-23 17:29 UTC, bwspenc approved these changes

2022-06-23 17:29 UTC, merged