Add ConcreteMoistureTimeIntegrationMassLumped
idaholab/blackbear pull request #328
Opened 2023-01-13 00:55 UTC by bwspenc

closes #327

2023-01-13 00:55 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1298651/) on f7e8eb4 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/blackbear/docs/PRs/328/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/blackbear/docs/PRs/328/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 9f556e2d16be8a119e76719b33c543e5b84bd231`

2023-01-13 01:19 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/1298697/) on 37e9fa6 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/blackbear/docs/PRs/328/site)

This comment will be updated on new commits.

2023-01-13 01:19 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1298700/) on 37e9fa6 wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>9f556e</th>
      <th colspan=4>#328 37e9fa</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>94.00%</td>
      <td>93.88%</td>
      <td>-0.12%</td>
      <td>85.00%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>1348</td>
      <td>1365</td>
      <td>+17</td>
      <td>17</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>86</td>
      <td>89</td>
      <td>+3</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/blackbear/docs/PRs/328/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/blackbear/docs/PRs/328/coverage)

## Warnings

- New new line coverage rate 85.00% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-01-13 03:54 UTC, jiangwen84 commented
Looks good. Only one minor comment.

2023-01-13 20:38 UTC, bwspenc commented
> Looks good. Only one minor comment.

Thanks, @jiangwen84 ! I can't see your comment for some reason. If you can point me to that, that would be great.

2023-01-16 18:59 UTC, jiangwen84 requested changes

2023-01-20 05:12 UTC, jiangwen84 submitted a review, later dismissed
Looks good to me.

2023-01-20 05:13 UTC, jiangwen84 commented
@bwspenc  I do not think I have the right to merge it. It looks good to me. You can have someone to merge it.

2023-01-20 21:24 UTC, dschwen commented on include/kernels/ConcreteMoistureTimeIntegrationMassLumped.h
> +
```suggestion
```

not needed

2023-01-20 21:25 UTC, dschwen commented on include/kernels/ConcreteMoistureTimeIntegrationMassLumped.h
> +  const MaterialProperty<Real> * _moisture_capacity; //  dW/dH
```suggestion
  const MaterialProperty<Real> * const  _moisture_capacity; //  dW/dH
```

2023-01-20 21:26 UTC, dschwen commented on src/kernels/ConcreteMoistureTimeIntegrationMassLumped.C
> +    _moisture_capacity = &getMaterialProperty<Real>("moisture_capacity");
```suggestion
  : MassLumpedTimeDerivative(parameters), 
    _moisture_capacity(hasMaterialProperty<Real>("moisture_capacity") ? &getMaterialProperty<Real>("moisture_capacity") : nullptr)
{
```

just a suggestion!

2023-01-20 21:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1310638/) on 78438da wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/blackbear/docs/PRs/328/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/blackbear/docs/PRs/328/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5c50563f716c8ac3ca4a0e97610526bea90b1282`

2023-01-20 22:09 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/1310683/) on 18241a0 wanted to post the following:

Your code requires style changes.  

A patch was auto generated and copied [here](https://mooseframework.inl.gov/blackbear/docs/PRs/328/clang_format/style.patch)  
You can directly apply the patch by running, in the top level of your repository:

`curl -s https://mooseframework.inl.gov/blackbear/docs/PRs/328/clang_format/style.patch | git apply -v`  

Alternatively, with your repository up to date and in the top level of your repository:

`git clang-format 5c50563f716c8ac3ca4a0e97610526bea90b1282`

2023-01-20 23:30 UTC, dschwen approved these changes

2023-01-20 23:30 UTC, merged