Add missing elements of SQA document templates
idaholab/blackbear pull request #338
Opened 2023-03-07 22:40 UTC by bwspenc

closes #127

2023-03-07 23:10 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/1394434/) on 9bb65aa wanted to post the following:

View the site [here](https://mooseframework.inl.gov/blackbear/docs/PRs/338/site)

This comment will be updated on new commits.

2023-03-07 23:10 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1394437/) on 9bb65aa wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/blackbear/docs/PRs/338/coverage)



This comment will be updated on new commits.

2023-03-07 23:28 UTC, cticenhour commented
Thanks @bwspenc! I will put this on my list to look at tomorrow.

2023-03-08 16:13 UTC, cticenhour requested changes

2023-03-08 16:13 UTC, cticenhour commented on doc/content/sqa/blackbear_srs.md
> +{{app}} provides access to a number of code objects that perform computations such as material behavior and boundary conditions. These objects each of makes their own physics-based assumptions, such
```suggestion
{{app}} provides access to a number of code objects that perform computations such as material behavior and boundary conditions. These objects each make their own physics-based assumptions, such as the units of the inputs and outputs. Those assumptions are described in the documentation for those individual objects.
```

2023-03-08 16:13 UTC, cticenhour commented on doc/content/sqa/blackbear_srs.md
> +- +{{app}} Developers+: These are the core developers of {{app}} module. They are responsible for designing, implementing, and maintaining the software, while following and enforcing its software dev
```suggestion
- +{{app}} Developers+: These are the core developers of {{app}}. They are responsible for designing, implementing, and maintaining the software, while following and enforcing its software development standards.
```

2023-03-08 16:13 UTC, cticenhour commented on doc/content/sqa/blackbear_srs.md
> +
```suggestion

!template! item key=information-management
{{app}} as well as the core MOOSE framework in its entirety will be made publicly available on an appropriate repository
hosting site. Day-to-day backups and security services will be provided by the hosting service. More
information about backups of the public repository on [!ac](INL)-hosted services can be found
on the following page: [sqa/github_backup.md]
!template-end!

!template! item key=policies-and-regulations
!include framework_srs.md start=policies-and-regulations-begin end=policies-and-regulations-finish
!template-end!

!template! item key=packaging
No special requirements are needed for packaging or shipping any media containing [!ac](MOOSE) and
the {{app}} source code. However, some [!ac](MOOSE)-based applications
that use the {{app}} code may be export-controlled, in which case all export control restrictions must
be adhered to when packaging and shipping media.
!template-end!

```

A couple missing sections - I'll go ahead and fill them in.

2023-03-08 22:35 UTC, cticenhour approved these changes

2023-03-08 22:37 UTC, cticenhour commented
@bwspenc This looks great to me! I don't have CCB authority in BlackBear, however, so someone else will need to step in for an official approval. Perhaps @lynnmunday?

2023-03-08 23:01 UTC, lynnmunday approved these changes

2023-03-08 23:03 UTC, merged